title: Thoughts about Stuff
author: mhmcdonald
email: mark@mcdonald.com
description: > # this means to ignore newlines until "baseurl:"
  Data Engineer, Husband, Dog Dad
theme: jekyll-theme-architect

# social links
twitter_username: hiesenburg # DO NOT include the @ character, or else the build will fail!
github_username:  mhmcdonald # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
